howdy: howdy.o
	ld -m elf_i386 howdy.o -o howdy

howdy.o: howdy.s
	as --32 howdy.s -o howdy.o

toupperastd: toupperastd.o
	ld -m elf_i386 toupperastd.o -o toupperastd

toupperastd.o: toupperastd.s
	as --32 toupperastd.s -o toupperastd.o

toupperstd: toupperstd.o
	ld -m elf_i386 toupperstd.o -o toupperstd

toupperstd.o: toupperstd.s
	as --32 toupperstd.s -o toupperstd.o

toupper: toupper.o
	ld -m elf_i386 toupper.o -o toupper

toupper.o: toupper.s
	as --32 toupper.s -o toupper.o

test_comments: test_comments.o
	ld -m elf_i386 test_comments.o -o test_comments

test_comments.o: test_comments.s
	as --32 test_comments.s -o test_comments.o